name: Android CI Unit Test and Code Analisys

on:
  push:
    pull_request:
      - '*'

jobs:
  build:
    name: Run Detekt and Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: ./gradlew build
      - name: Detekt
        uses: natiginfo/action-detekt-all@1.12.0-RC1
        with:
          args: --fail-fast --config config/detekt/detekt-config.yml
      - name: Unit tests
        run: ./gradlew testDebugUnitTest --stacktrace